version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - maria_db
    environment:
      spring.datasource.driverClassName: "org.mariadb.jdbc.Driver"
      spring.datasource.url: "jdbc:mariadb://maria_db:3306/compagnie"
      spring.datasource.username: "root"
      spring.datasource.password: "root"
      server.port: 8080
      server.address: 0.0.0.0
  maria_db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=compagnie
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=rootpassword,